# Generated by Django 5.2.7 on 2026-04-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='department',
            field=models.CharField(choices=[('development', 'Development'), ('hr', 'Human Resources (HR)'), ('finance', 'Finance'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('operations', 'Operations')], default='development', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='designation',
            field=models.CharField(choices=[('software_engineer', 'Software Engineer'), ('senior_developer', 'Senior Developer'), ('junior_developer', 'Junior Developer'), ('ceo', 'CEO'), ('coo', 'COO'), ('cto', 'CTO'), ('hr_manager', 'HR Manager'), ('accountant', 'Accountant'), ('team_lead', 'Team Lead'), ('intern', 'Intern')], default='software_engineer', max_length=50),
        ),
    ]
