# Generated by Django 5.2.7 on 2026-04-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('wfh', 'Work from Home'), ('holiday', 'Holiday')], default='present', max_length=20),
        ),
    ]
